sylius_grid:
    grids:
        sylius_shop_account_order_seller:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.order.class%"
                    repository:
                        method: createsellerByCustomerAndChannelIdQueryBuilder
                        arguments:
                            - "expr:service('sylius.context.customer').getCustomer().getId()"
                            - "expr:service('sylius.context.channel').getChannel().getId()"
            sorting:
                checkoutCompletedAt: desc
            fields:
                number:
                    type: twig
                    label: sylius.ui.number
                    sortable: ~
                    options:
                        template: "@SyliusShop/Account/Order/Grid/Field/number.html.twig"
                checkoutCompletedAt:
                    type: datetime
                    label: sylius.ui.date
                    sortable: ~
                    options:
                        format: m/d/Y
                shippingAddress:
                    type: twig
                    label: sylius.ui.ship_to
                    options:
                        template: "@SyliusShop/Account/Order/Grid/Field/address.html.twig"
                total:
                    type: twig
                    label: sylius.ui.total
                    path: .
                    sortable: total
                    options:
                        template: "@SyliusShop/Account/Order/Grid/Field/total.html.twig"
                state:
                    type: twig
                    label: sylius.ui.state
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/label.html.twig"
                        vars:
                            labels: "@SyliusShop/Account/Order/Label/State"
            actions:
                item:
                    show:
                        type: show
                        label: sylius.ui.show
                        options:
                            link:
                                route: sylius_shop_account_order_show
                                parameters:
                                    number: resource.number
                    pay:
                        type: pay
                        label: sylius.ui.pay
                        options:
                            link:
                                route: sylius_shop_order_show
                                parameters:
                                    tokenValue: resource.tokenValue

        sylius_admin_customer:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.customer.class%"
                    repository:
                        method: createcustomerListQueryBuilder

            sorting:
                createdAt: desc
            fields:
                firstName:
                    type: string
                    label: sylius.ui.first_name
                    sortable: ~
                lastName:
                    type: string
                    label: sylius.ui.last_name
                    sortable: ~
                email:
                    type: string
                    label: sylius.ui.email
                    sortable: ~
                createdAt:
                    type: datetime
                    label: sylius.ui.registration_date
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    path: .
                    options:
                        template: "@SyliusAdmin/Customer/Grid/Field/enabled.html.twig"
                verified:
                    type: twig
                    label: sylius.ui.verified
                    path: .
                    options:
                        template: "@SyliusAdmin/Customer/Grid/Field/verified.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [email, firstName, lastName]
            actions:
                main:
                    create:
                        type: create
                item:
                    show_orders:
                        type: show
                        label: sylius.ui.show_orders
                        options:
                            link:
                                route: sylius_admin_customer_order_index
                                parameters:
                                    id: resource.id
                    show:
                        type: show
                    update:
                        type: update

        app_admin_seller:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.customer.class%"
                    repository:
                        method: createsellerListQueryBuilder

            sorting:
                createdAt: desc
            fields:
                firstName:
                    type: string
                    label: sylius.ui.first_name
                    sortable: ~
                lastName:
                    type: string
                    label: sylius.ui.last_name
                    sortable: ~
                email:
                    type: string
                    label: sylius.ui.email
                    sortable: ~
                createdAt:
                    type: datetime
                    label: sylius.ui.registration_date
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    path: .
                    options:
                        template: "@SyliusAdmin/Customer/Grid/Field/enabled.html.twig"
                verified:
                    type: twig
                    label: sylius.ui.verified
                    path: .
                    options:
                        template: "@SyliusAdmin/Customer/Grid/Field/verified.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [email, firstName, lastName]
            actions:
                main:
                    create:
                        type: create
                item:
                    show_orders:
                        type: show
                        label: sylius.ui.show_orders
                        options:
                            link:
                                route: sylius_admin_customer_order_index
                                parameters:
                                    id: resource.id
                    show:
                        type: show
                    update:
                        type: update



        sylius_admin_product:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%", $taxonId]
            sorting:
                code: asc
            fields:
                image:
                    type: twig
                    label: sylius.ui.image
                    path: .
                    options:
                        template: "@SyliusAdmin/Product/Grid/Field/image.html.twig"
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
                mainTaxon:
                    type: twig
                    label: sylius.ui.main_taxon
                    options:
                        template: "@SyliusAdmin/Product/Grid/Field/mainTaxon.html.twig"
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, translation.name]
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: links
                        label: sylius.ui.create
                        options:
                            class: primary
                            icon: plus
                            header:
                                icon: cube
                                label: sylius.ui.type
                            links:
                                simple:
                                    label: sylius.ui.simple_product
                                    icon: plus
                                    route: sylius_admin_product_create_simple

                item:
                    update:
                        type: update
                    delete:
                        type: delete
                subitem:
                    variants:
                        type: links
                        label: sylius.ui.manage_variants
                        options:
                            icon: cubes
                            links:
                                index:
                                    label: sylius.ui.list_variants
                                    icon: list
                                    route: sylius_admin_product_variant_index
                                    parameters:
                                        productId: resource.id
                                create:
                                    label: sylius.ui.create
                                    icon: plus
                                    route: sylius_admin_product_variant_create
                                    parameters:
                                        productId: resource.id
                                generate:
                                    label: sylius.ui.generate
                                    icon: random
                                    route: sylius_admin_product_variant_generate
                                    visible: resource.hasOptions
                                    parameters:
                                        productId: resource.id
                bulk:
                    delete:
                        type: delete




